import {
  Users, Bell, CreditCard, FileText, MessageCircle, Phone,
  CheckCircle2, BarChart2, Shield,
  Headphones, Package, Globe, TrendingUp,
  IndianRupee, BookOpen, Megaphone, Wallet, Store,
  Building2, Zap
} from "lucide-react";

export const products = [
  {
    name: "NewBiz CRM",
    tagline: "Sales & lead management for small teams",
    desc: "A complete CRM with Kanban pipeline, GST invoicing, PhonePe payments, reminders, helpdesk, and team collaboration — built specifically for Indian SMEs.",
    icon: Users,
    color: "from-blue-500 to-indigo-600",
    iconBg: "bg-blue-50 text-blue-600",
    status: "beta" as const,
    href: "/signup",
    cta: "Try Free — Beta Access",
    features: ["Lead pipeline", "GST invoicing", "PhonePe payments", "Team roles", "Push reminders"],
  },
  {
    name: "NewBiz Books",
    tagline: "Simple accounting for non-accountants",
    desc: "Track income, expenses, GST returns, and generate P&L — without needing a CA for day-to-day bookkeeping.",
    icon: BookOpen,
    color: "from-emerald-500 to-teal-600",
    iconBg: "bg-emerald-50 text-emerald-600",
    status: "soon" as const,
    href: "#notify",
    cta: "Notify Me",
    features: ["Income & expense tracking", "GST returns", "P&L reports", "Bank reconciliation"],
  },
  {
    name: "NewBiz Campaigns",
    tagline: "WhatsApp & email marketing made simple",
    desc: "Send bulk WhatsApp messages, email campaigns, and follow-up sequences to your customer list — with real open & click tracking.",
    icon: Megaphone,
    color: "from-rose-500 to-pink-600",
    iconBg: "bg-rose-50 text-rose-600",
    status: "soon" as const,
    href: "#notify",
    cta: "Notify Me",
    features: ["Bulk WhatsApp", "Email campaigns", "Open & click tracking", "Drip sequences"],
  },
  {
    name: "NewBiz Pay",
    tagline: "Unified payments & collections dashboard",
    desc: "Accept UPI, cards, and net banking; send payment links; auto-reconcile with your invoices; and get a real-time collections dashboard.",
    icon: Wallet,
    color: "from-amber-500 to-orange-600",
    iconBg: "bg-amber-50 text-amber-600",
    status: "soon" as const,
    href: "#notify",
    cta: "Notify Me",
    features: ["UPI & card payments", "Payment links", "Auto-reconciliation", "Collections report"],
  },
  {
    name: "NewBiz Store",
    tagline: "Sell online with zero coding",
    desc: "A lightweight online store builder — add your products, set prices, share your store link, and start selling in under an hour.",
    icon: Store,
    color: "from-violet-500 to-purple-600",
    iconBg: "bg-violet-50 text-violet-600",
    status: "soon" as const,
    href: "#notify",
    cta: "Notify Me",
    features: ["Product catalogue", "Order management", "WhatsApp checkout", "Delivery tracking"],
  },
  {
    name: "NewBiz HR",
    tagline: "Attendance, payroll & leave for small teams",
    desc: "Manage employee attendance via mobile, run monthly payroll with PF/ESI deductions, and handle leave requests — all without HR software complexity.",
    icon: Building2,
    color: "from-cyan-500 to-blue-600",
    iconBg: "bg-cyan-50 text-cyan-600",
    status: "soon" as const,
    href: "#notify",
    cta: "Notify Me",
    features: ["Attendance & leave", "Payroll + PF/ESI", "Salary slips", "Employee portal"],
  },
];

export const crmFeatures = [
  { icon: Users, title: "Lead Pipeline", desc: "Drag-drop Kanban board + list view. Never lose track of a deal.", color: "bg-blue-50 text-blue-600" },
  { icon: MessageCircle, title: "One-Tap Contact", desc: "WhatsApp, call, email or SMS any lead in one tap — mobile or desktop.", color: "bg-green-50 text-green-600" },
  { icon: Bell, title: "Smart Reminders", desc: "Push notifications with sound. Works even when the tab is in the background.", color: "bg-purple-50 text-purple-600" },
  { icon: FileText, title: "GST Invoicing", desc: "Professional invoices with GSTIN, HSN/SAC, tax split. Download as PDF instantly.", color: "bg-amber-50 text-amber-600" },
  { icon: CreditCard, title: "PhonePe Payments", desc: "Accept online payments, track dues, and mark paid in one click.", color: "bg-rose-50 text-rose-600" },
  { icon: BarChart2, title: "Reports & Insights", desc: "Pipeline value, conversion rates, revenue trends — real-time.", color: "bg-indigo-50 text-indigo-600" },
  { icon: Headphones, title: "Support Helpdesk", desc: "Manage customer tickets, set SLAs, and respond — no extra tool.", color: "bg-teal-50 text-teal-600" },
  { icon: Package, title: "Product Catalogue", desc: "Maintain your product/service list. Add to invoices in one click.", color: "bg-orange-50 text-orange-600" },
];

export const plans = [
  {
    name: "Free",
    price: "₹0",
    period: "forever",
    desc: "Get started, no risk",
    borderColor: "border-gray-200",
    badge: null,
    highlight: false,
    features: ["50 leads", "1 member", "5 invoices/mo", "Basic pipeline", "Push reminders"],
    cta: "Start Free",
    href: "/signup",
  },
  {
    name: "Starter",
    price: "₹999",
    period: "/month",
    desc: "For growing businesses",
    borderColor: "border-blue-500",
    badge: "Most Popular",
    highlight: true,
    features: ["500 leads", "3 members", "50 invoices/mo", "Reminders & pipeline", "Email templates", "WhatsApp & calling"],
    cta: "Get Starter",
    href: "/signup",
  },
  {
    name: "Growth",
    price: "₹2,499",
    period: "/month",
    desc: "For scaling teams",
    borderColor: "border-purple-400",
    badge: null,
    highlight: false,
    features: ["2,000 leads", "10 members", "200 invoices/mo", "All Starter features", "Webhooks & API", "Audit log"],
    cta: "Start Growth",
    href: "/signup",
  },
  {
    name: "Pro",
    price: "₹4,999",
    period: "/month",
    desc: "Unlimited everything",
    borderColor: "border-gray-700",
    badge: "Best Value",
    highlight: false,
    features: ["Unlimited leads", "Unlimited members", "Unlimited invoices", "All Growth features", "Priority support", "Custom branding"],
    cta: "Go Pro",
    href: "/signup",
  },
];

export const whyUs = [
  { icon: IndianRupee, title: "Priced for Indian SMEs", desc: "Not ₹10,000/month tools built for US enterprises. Real pricing built around what Indian businesses can afford." },
  { icon: Zap, title: "Up and running in 15 min", desc: "Sign up, import leads from Excel, and start working. No IT team, no week-long setup." },
  { icon: Shield, title: "Your data stays yours", desc: "Hosted on secure infrastructure. GDPR & data protection built in. We never sell your data." },
  { icon: Headphones, title: "Hand-holding support", desc: "We don't just give you a login. Our team sets it up with you, trains your staff, and checks in regularly." },
  { icon: Globe, title: "Works on every device", desc: "Full-featured PWA. Works on your laptop in the office and your phone in the field — even on slow networks." },
  { icon: TrendingUp, title: "Grows with you", desc: "Start free on one product. Add more tools as you grow. Cancel any product, any time. No lock-in." },
];

export const testimonials = [
  {
    name: "Rajesh Sharma",
    role: "Owner, RS Electricals",
    city: "Jaipur",
    product: "NewBiz CRM",
    quote: "Before NewBiz CRM I was tracking leads in WhatsApp groups and a notebook. Now I close 40% more deals because nothing slips through.",
    stars: 5,
  },
  {
    name: "Priya Nair",
    role: "Founder, Bloom Events",
    city: "Kochi",
    product: "NewBiz CRM",
    quote: "The GST invoicing alone saved us ₹5,000/month on the CA bill. Everything is in one place and the team loves it.",
    stars: 5,
  },
  {
    name: "Amit Desai",
    role: "Director, Desai Exports",
    city: "Surat",
    product: "NewBiz CRM",
    quote: "NewBiz actually helped us set up the whole thing. It wasn't just a tool sale — they walked us through every feature.",
    stars: 5,
  },
];
